# REFERENCE 
# http://research.cs.wisc.edu/htcondor/manual/
# https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookXrootdService

#---------------------------------------------
# voms-proxy-init --voms cms, to use T2 files
# hplusAnalyzer.sh is run by condor_submit
# Arguments are passed to hplusAnalyzer.sh
#---------------------------------------------

Universe              = vanilla
x509userproxy         = /afs/cern.ch/user/r/rverma/x509up_u93032
#use_x509userproxy    = true
Executable            = hplusAnalyzer.sh
Arguments             = /cms/store/user/rverma/multicrab_29April17/MuMC_20170429/TTJets_MuMC_20170429/TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/TTJets_MuMC_20170429/170429_110042/0000/TTJets_MuMC_20170429_Ntuple_9.root TTJets_MuMC_20170429_Ntuple_9 TTJets_MuMC_20170429_Ntuple_9 $(Process) $(Cluster)

#---------------------------------------------
# hplusAnalyzer.C output are stored in .stdout
# all kind of errors are stores in .stderr
# CPU usage, RAM etc are stored in .log
#---------------------------------------------

Output                = condor_out_$(Process)_$(Cluster).stdout
Error                 = condor_out_$(Process)_$(Cluster).stderr
Log                   = condor_out_$(Process)_$(Cluster).log
Notification          = Error

#---------------------------------------------
# transfer output from remote machine to T2
# put the condor batch submission in queue 
#---------------------------------------------

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
Queue

